### ISSUE TITLE
"ImportError: cannot import name 'numba_range' from 'brainpy.tools'" in version 2.4.4.post1

### ISSUE THREAD

**Issue by CloudyDory** [brainpy/BrainPy#462]
- [x] Check for duplicate issues.
- [x] Provide a complete example of how to reproduce the bug, wrapped in triple backticks like this:
- [x] If applicable, include full error messages/tracebacks.

Hi, I have just upgraded brainpy from version 2.4.3.post5 to version 2.4.4.post1. In version 2.4.3 everything works fine. However, immediately after upgrading to 2.4.4, `import brainpy` gives the following error:

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\xxx\miniconda3\Lib\site-packages\brainpy\__init__.py", line 24, in <module>
    from brainpy import (
  File "C:\Users\xxx\miniconda3\Lib\site-packages\brainpy\initialize\__init__.py", line 9, in <module>
    from .generic import *
  File "C:\Users\xxx\miniconda3\Lib\site-packages\brainpy\initialize\generic.py", line 10, in <module>
    from brainpy.types import Shape, Array
  File "C:\Users\xxx\miniconda3\Lib\site-packages\brainpy\types.py", line 3, in <module>
    from brainpy._src.types import (
  File "C:\Users\xxx\miniconda3\Lib\site-packages\brainpy\_src\types.py", line 9, in <module>
    from brainpy._src import connect as conn
  File "C:\Users\xxx\miniconda3\Lib\site-packages\brainpy\_src\connect\__init__.py", line 11, in <module>
    from .random_conn import *
  File "C:\Users\xxx\miniconda3\Lib\site-packages\brainpy\_src\connect\random_conn.py", line 11, in <module>
    from brainpy.tools import numba_seed, numba_jit, numba_range, format_seed
ImportError: cannot import name 'numba_range' from 'brainpy.tools' (C:\Users\xxx\miniconda3\Lib\site-packages\brainpy\tools\__init__.py)
```

I am using Python 3.11 with Miniconda. Thanks!

**Comment by CloudyDory** [comment]
I install brainpy by `pip install -U brainpy`. Have tried completely remove brainpy and reinstall, but still doesn't work.

**Comment by chaoming0625** [comment]
I have tested it just now. It works, no error report. Please check your installation. Maybe something is wrong?

<img width="496" alt="image" src="https://github.com/brainpy/BrainPy/assets/14275596/3db830af-ab80-4894-b0e7-071129f0a878">

**Comment by CloudyDory** [comment]
Hi, I have tried removing `brainpylib` and `jax[cpu]`, and then reinstall them with `brainpy` again. This time it works. Thanks!
